#ifndef __RYU_MAIN__
#define __RYU_MAIN__

/*
  Ryu subsystem

Ryu is an entity management system. Each entity is a 64bit number identifier with components attaching to, like an ECS.
32 bits for the index, 16 for the generation counter and the last 16 for the world id.

In Ryu, there is a concept of world, which is a container of entities. Entities generated by a world, belong to the world. Entity movement between worlds is impossible.
Worlds handles are 32 bit unsigned integers with 16 bits for identity and 16 bits for the generation counting.

World generation is done by Ryu, while entity generation is done by worlds.
 */

#include <stdbool.h>
#include <stdint.h>

#define RYU_ENTITY_INDEX_MASK 0xFFFFFFFF00000000
#define RYU_ENTITY_GENERATION_MASK 0x00000000FFFF0000
#define RYU_ENTITY_WORLD_MASK 0x000000000000FFFF

#define RYU_ENTITY_INDEX(ent) (((ent) >> 32) & 0xFFFFFFFF)
#define RYU_ENTITY_GENERATION(ent) (((ent) >> 16) & 0x00000000FFFF)
#define RYU_ENTITY_WORLD(ent) ((ent) & RYU_ENTITY_WORLD_MASK)

#define RYU_WORLD_INDEX_MASK 0xFF00
#define RYU_WORLD_GENERATION_MASK 0x00FF

#define RYU_WORLD_INDEX(ent) (((ent) >> 8) & 0xFFFF)
#define RYU_WORLD_GENERATION(ent) ((ent) & RYU_WORLD_GENERATION_MASK)

typedef uint64_t Entity;
typedef uint16_t RyuWorld;

/* creates a new ryu world */
RyuWorld ryu_newWorld(void);

/* returns true if the world handle is valid */
bool ryu_isWorldValid(RyuWorld);

/* frees the given world */
void ryu_destroyWorld(RyuWorld);

/* creates an entity in the world */
Entity ryu_newEntity(RyuWorld);

/* returns true if entity handle is valid */
bool ryu_isEntityValid(Entity);

/* destroy the entity
   Notice: Not immediately. Happens after the flush.
 */
void ryu_destroyEntity(Entity);

/* teels if the entity is pending to be destroyed in the next flush */
bool ryu_isEntityPending(Entity);

/* destroys entities pending in the world */
void ryu_flush(RyuWorld);

#endif //__RYU_MAIN__
